package historycompare

import (
	augmentcontract "issueops/internal/contract/selfaugment"
)

type SelfAugmentCompareResult = augmentcontract.SelfAugmentCompareResult
type SelfAugmentHistoryEntry = augmentcontract.SelfAugmentHistoryEntry
type SelfAugmentHistoryResult = augmentcontract.SelfAugmentHistoryResult
type SelfAugmentHistoryRetention = augmentcontract.SelfAugmentHistoryRetention
type SelfAugmentHistoryRetentionOptions = augmentcontract.SelfAugmentHistoryRetentionOptions
type SelfAugmentHistorySkipped = augmentcontract.SelfAugmentHistorySkipped
type SelfAugmentSlowStep = augmentcontract.SelfAugmentSlowStep
type SelfAugmentSlowStepRegression = augmentcontract.SelfAugmentSlowStepRegression
type SelfAugmentStateSnapshot = augmentcontract.SelfAugmentStateSnapshot
type SelfAugmentStepBudgetRegression = augmentcontract.SelfAugmentStepBudgetRegression
type SelfAugmentStepDurationStat = augmentcontract.SelfAugmentStepDurationStat
type SelfAugmentSummary = augmentcontract.SelfAugmentSummary
