package quality

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

const productSource = "package fixture\nfunc Product() { if true {} }\n"

func writeProductFixture(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func sourceGit(t *testing.T, root string, args ...string) {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = root
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %s: %v", args, output, err)
	}
}

func assertProductCollectors(t *testing.T, root string, wanted []string) {
	t.Helper()
	functions, warnings := CollectBranchFunctions(root)
	if len(warnings) != 0 {
		t.Fatalf("warnings: %v", warnings)
	}
	var got []string
	var signal, noise int
	for _, name := range wanted {
		s, n, err := snrCountFile(filepath.Join(root, name))
		if err != nil {
			t.Fatal(err)
		}
		signal += s
		noise += n
	}
	for _, fn := range functions {
		got = append(got, filepath.ToSlash(fn.File))
	}
	sort.Strings(got)
	sort.Strings(wanted)
	if !reflect.DeepEqual(got, wanted) {
		t.Errorf("product files = %q, want %q", got, wanted)
	}
	result, err := ComputeCodeSNR(root)
	if err != nil {
		t.Fatal(err)
	}
	if result.SignalLines != signal || result.NoiseLines != noise {
		t.Errorf("SNR = %+v, want signal=%d noise=%d", result, signal, noise)
	}
}

func TestProductionSourceGitScope(t *testing.T) {
	root := t.TempDir()
	sourceGit(t, root, "init", "-q")
	wanted := []string{"tracked.go", "tracked-ignored.go", "fresh.go", "space name.go", "newline\nname.go", "ordinary.go", "src/nested.go"}
	for _, name := range wanted {
		writeProductFixture(t, root, name, productSource)
	}
	writeProductFixture(t, root, "ordinary.go", "// generated documentation is ordinary prose\n"+productSource)
	writeProductFixture(t, root, "deleted.go", productSource)
	sourceGit(t, root, "add", "tracked.go", "tracked-ignored.go", "deleted.go", "src/nested.go")
	sourceGit(t, root, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "commit", "-qm", "fixture")
	sourceGit(t, root, "rm", "-q", "deleted.go")
	writeProductFixture(t, root, ".gitignore", "ignored/\ntracked-ignored.go\n.issueops/\n")
	excluded := []string{"ignored/repro.go", ".issueops/evidence/repro.go", ".issueops/tmp/repro.go", ".issueops/issues/521/repro.go", "testdata/sample.go", "vendor/sample.go", "node_modules/sample.go", ".codegraph/sample.go", ".issueops-runtime/sample.go", "bin/sample.go", "product_test.go"}
	for _, name := range excluded {
		writeProductFixture(t, root, name, productSource)
	}
	// Exclusions also apply to tracked fixtures and generated code.
	sourceGit(t, root, "add", "-f", "testdata/sample.go", ".issueops/evidence/repro.go")
	writeProductFixture(t, root, "generated.go", "// Code generated by fixture. DO NOT EDIT.\n"+productSource)
	sourceGit(t, root, "add", "generated.go")
	outside := t.TempDir()
	writeProductFixture(t, outside, "outside.go", productSource)
	if err := os.Symlink(filepath.Join(outside, "outside.go"), filepath.Join(root, "link.go")); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "linked")); err != nil {
		t.Fatal(err)
	}
	assertProductCollectors(t, root, wanted)
	t.Run("nested root", func(t *testing.T) { assertProductCollectors(t, filepath.Join(root, "src"), []string{"nested.go"}) })
	t.Run("tracked ancestor symlink", func(t *testing.T) {
		if err := os.Rename(filepath.Join(root, "src"), filepath.Join(root, "old-src")); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(outside, filepath.Join(root, "src")); err != nil {
			t.Fatal(err)
		}
		functions, warnings := CollectBranchFunctions(root)
		if len(warnings) != 0 {
			t.Fatal(warnings)
		}
		for _, fn := range functions {
			if fn.File == "src/nested.go" {
				t.Fatal("followed tracked ancestor symlink")
			}
		}
	})
}

func TestProductionSourceNonGitAndMissingGit(t *testing.T) {
	for _, missingGit := range []bool{false, true} {
		t.Run(map[bool]string{false: "non-Git", true: "no executable"}[missingGit], func(t *testing.T) {
			root := t.TempDir()
			if missingGit {
				t.Setenv("PATH", t.TempDir())
			}
			writeProductFixture(t, root, "product.go", productSource)
			for _, name := range []string{".issueops/evidence/repro.go", "testdata/sample.go", "bin/sample.go"} {
				writeProductFixture(t, root, name, productSource)
			}
			writeProductFixture(t, root, "generated.go", "// Code generated by fixture. DO NOT EDIT.\n"+productSource)
			assertProductCollectors(t, root, []string{"product.go"})
		})
	}
}

func TestProductionSourceGitWorktree(t *testing.T) {
	repo := t.TempDir()
	sourceGit(t, repo, "init", "-q")
	writeProductFixture(t, repo, "product.go", productSource)
	sourceGit(t, repo, "add", ".")
	sourceGit(t, repo, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "commit", "-qm", "fixture")
	worktree := filepath.Join(t.TempDir(), "worktree")
	sourceGit(t, repo, "worktree", "add", "-q", "-b", "quality-fixture", worktree)
	writeProductFixture(t, worktree, ".gitignore", "ignored/\n")
	writeProductFixture(t, worktree, "ignored/repro.go", productSource)
	writeProductFixture(t, worktree, "new.go", productSource)
	assertProductCollectors(t, worktree, []string{"product.go", "new.go"})
}

func TestProductionSourceGitFailureDoesNotFallback(t *testing.T) {
	root := t.TempDir()
	sourceGit(t, root, "init", "-q")
	writeProductFixture(t, root, "product.go", productSource)
	writeProductFixture(t, root, ".git/index", "invalid index")
	functions, warnings := CollectBranchFunctions(root)
	if len(warnings) == 0 || len(functions) != 0 {
		t.Fatalf("Git failure hidden: functions=%v warnings=%v", functions, warnings)
	}
	if _, err := ComputeCodeSNR(root); err == nil {
		t.Fatal("SNR hid Git failure")
	}
}

func TestProductionSourceReadErrorPreservesPartialBranches(t *testing.T) {
	root := t.TempDir()
	writeProductFixture(t, root, "healthy.go", productSource)
	writeProductFixture(t, root, "unreadable.go", productSource)
	path := filepath.Join(root, "unreadable.go")
	if err := os.Chmod(path, 0); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(path, 0644) })
	functions, warnings := CollectBranchFunctions(root)
	if len(warnings) == 0 || len(functions) != 1 || functions[0].File != "healthy.go" {
		t.Fatalf("partial result lost: functions=%v warnings=%v", functions, warnings)
	}
	if _, err := ComputeCodeSNR(root); err == nil {
		t.Fatal("SNR hid read error")
	}
}

func TestProductionSourceGitCommandBoundaries(t *testing.T) {
	root := t.TempDir()
	t.Run("output limit", func(t *testing.T) {
		if _, err := sourceGitOutput(context.Background(), root, 1, "--version"); err == nil || !strings.Contains(err.Error(), "output exceeds") {
			t.Fatalf("output limit: %v", err)
		}
	})
	t.Run("deadline", func(t *testing.T) {
		ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(-time.Second))
		defer cancel()
		if _, err := sourceGitOutput(ctx, root, 1024, "--version"); !errors.Is(err, context.DeadlineExceeded) {
			t.Fatalf("deadline: %v", err)
		}
	})
	t.Run("stderr is not a filename", func(t *testing.T) {
		output, err := sourceGitOutput(context.Background(), root, 1024, "-c", "alias.quality-fixture=!printf 'healthy.go\\0'; printf diagnostic >&2", "quality-fixture")
		if err != nil || output != "healthy.go\x00" {
			t.Fatalf("stdout/stderr mixed: %q %v", output, err)
		}
	})
	t.Run("missing Git in workspace", func(t *testing.T) {
		sourceGit(t, root, "init", "-q")
		writeProductFixture(t, root, "product.go", productSource)
		t.Setenv("PATH", t.TempDir())
		if _, err := ComputeCodeSNR(root); err == nil {
			t.Fatal("marked Git workspace silently fell back")
		}
	})
}

func TestProductionSourceParseWarningAndRelativeRoot(t *testing.T) {
	root := t.TempDir()
	writeProductFixture(t, root, "healthy.go", productSource)
	writeProductFixture(t, root, "broken.go", "package fixture\nfunc Broken( {\n")
	t.Chdir(root)
	functions, warnings := CollectBranchFunctions(".")
	if len(functions) != 1 || functions[0].File != "healthy.go" || len(warnings) != 1 {
		t.Fatalf("parse/relative root contract: %v %v", functions, warnings)
	}
	if _, err := ComputeCodeSNR("."); err != nil {
		t.Fatalf("SNR should still classify text: %v", err)
	}
}

func TestProductionSourceExcludedRoot(t *testing.T) {
	for _, gitWorkspace := range []bool{false, true} {
		t.Run(map[bool]string{false: "non-Git", true: "Git"}[gitWorkspace], func(t *testing.T) {
			root := t.TempDir()
			if gitWorkspace {
				sourceGit(t, root, "init", "-q")
			}
			for _, directory := range []string{"testdata", ".issueops/evidence", ".issueops/tmp", ".issueops/issues/521", "vendor", "bin"} {
				writeProductFixture(t, root, directory+"/repro.go", productSource)
				if gitWorkspace {
					sourceGit(t, root, "add", "-f", directory+"/repro.go")
				}
				functions, warnings := CollectBranchFunctions(filepath.Join(root, directory))
				if len(functions) != 0 || len(warnings) != 0 {
					t.Errorf("%s root: functions=%v warnings=%v", directory, functions, warnings)
				}
				snr, err := ComputeCodeSNR(filepath.Join(root, directory))
				if err != nil || snr.TotalLines != 0 {
					t.Errorf("%s root SNR=%+v error=%v", directory, snr, err)
				}
			}
			writeProductFixture(t, root, "src/product.go", productSource)
			assertProductCollectors(t, filepath.Join(root, "src"), []string{"product.go"})
		})
	}
}

func TestProductionSourceNestedRepositoryHasOwnScope(t *testing.T) {
	root := filepath.Join(t.TempDir(), "testdata", "repository")
	if err := os.MkdirAll(root, 0755); err != nil {
		t.Fatal(err)
	}
	sourceGit(t, root, "init", "-q")
	writeProductFixture(t, root, "product.go", productSource)
	assertProductCollectors(t, root, []string{"product.go"})
}
